# Travis continuous integration system configuration file.
# Read more at: http://docs.travis-ci.com/user/customizing-the-build/

sudo: required
dist: trusty
group: edge
language: node_js

cache:
  directories:
    - node_modules
    - .tools

addons:
  # Run tests that require a browser on SauceLabs CI provider. Learn more at: https://saucelabs.com
  sauce_connect: true
  # Enables sauce labs for pull requests.
  jwt:
    secure: NfCHCQULhYH0JUobRTBGF4QuQxMoj0Zs9iH71oSgI+eW7ClpNDp0cEF8h+IelTdPGQY7T9Kz4tyrZkUeXD5Mi/jjZT0YnjxSS8Ip6rRRxPDCWEmxbhOrZTEBXYfa4vqCY7rLnor8g579WOZ+RyoiotPC8tlc955nEgBk1jDxyAgXoUy0SdA/05r6A2IqKfs95u+yq0nsYqYJBj/3onx2SQv94eMQ7qq9GMhsAWMoNzLsBfU8AkZLsJ2w/W2p9tQURNk1hgCEewMwe6E6+G3XMAnDoIXBHkRAU335FBUE+f2kZ5Gl3GKE8pvWJaUWLePzfBvlmzCi4GW6lPlrRE5m+3wiiSzcbEAJnWOVPBrD/6mogYaJ5RijKzWk5o91eV8lU/lttp0hpH7PdWj1CEZk7EmyKO7ZF7ScALOZgs/dGyGgWcAvA0zwCDzdxXIitq9Eegc0xU+bB9jyJgi4dV9H1T1prwtS/TdhBU6sXKEjFVIgPUQa/TqBgaSs634kqRueH3bNfSD8Nf655AFeSgwdGiW0pBDm/WESftFWBMW3eV+KYtBFmGU/b3g+eEmd04j+lIOkK6EzU1QetUCKhpeMc5509So/+k4XghPHldWYzRldpY0kbp32VnAY8egsDdAHxgPrs2mTIDD1W//D/XJI9J072/z47GN4Af5zryz/3Nc=

matrix:
  include:
    - node_js: 8.6.0
      env:
      - BUILD_SUITE=integration-test
      - SAUCE_USERNAME=k8s-dashboard-ci
      - KUBE_DASHBOARD_KUBECONFIG=$HOME/.kube/config
    - node_js: 8.6.0
      env:
      - BUILD_SUITE=code-test
      - SAUCE_USERNAME=k8s-dashboard-ci

before_script:
  - eval "$(gimme 1.9.2)"
  - docker --version

script:
  - 'if [ ${BUILD_SUITE} = "integration-test" ]; then
      ./build/ci/start-cluster.sh;

      ./node_modules/.bin/gulp check:ci --heapsterServerHost "http://localhost:8082";
    else
       NODE_ENV=test npm run check;
    fi'

after_success:
  - 'if [ ${BUILD_SUITE} = "integration-test" ]; then
      if ([ ${TRAVIS_PULL_REQUEST} = "false" ] && [ -n "${DOCKER_USER}" && [ -n "${DOCKER_PASS}" ]); then
        docker login -u $DOCKER_USER -p $DOCKER_PASS;
        npm run docker-push:head:cross;
      else
        echo "This is not master build or Docker credentials are missing. Image will not be pushed."
      fi
    else
      bash <(curl -s https://codecov.io/bash);
    fi'
